name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t alirhayem/docker-cicd-test:latest .

      - name: Push Docker image
        run: |
          docker push alirhayem/docker-cicd-test:${{ github.sha }}
          docker push alirhayem/docker-cicd-test:latest

      - name: Force stop and remove existing Docker container (if exists)
        run: |
          docker rm -f docker-cicd-test || true
          sleep 5  # Add a delay to ensure the container is fully removed

      - name: Pull and run Docker container
        run: |
          docker pull alirhayem/docker-cicd-test:latest
          docker run -d -p 8000:8000 --name docker-cicd-test alirhayem/docker-cicd-test:latest

      - name: Inspect Docker logs
        run: |
          docker logs docker-cicd-test
