name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t alirhayem/docker-cicd-test:${{ github.sha }} .
          docker push alirhayem/docker-cicd-test:${{ github.sha }}

      - name: Pull Latest Docker Image
        run: |
          docker pull alirhayem/docker-cicd-test:${{ github.sha }}

      - name: Remove Old Container
        run: |
          docker rm -f cicd-test-container || true

      - name: Remove Old Image
        run: |
          docker rmi alirhayem/docker-cicd-test:${{ github.sha }} || true

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name cicd-test-container alirhayem/docker-cicd-test:${{ github.sha }}
