name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Pull the latest image from Docker Hub (Optional)
      # This step ensures that you have the latest image if needed for incremental builds or caching.
      - name: Pull Latest Docker Image
        run: |
          docker pull alirhayem/docker-cicd-test:latest || true

      # Step 4: Build the Docker image from the Dockerfile
      - name: Build Docker Image
        run: |
          docker build -t alirhayem/docker-cicd-test:${{ github.sha }} -t alirhayem/docker-cicd-test:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push alirhayem/docker-cicd-test:${{ github.sha }}
          docker push alirhayem/docker-cicd-test:latest

      # Step 6: Run the Docker container
      - name: Run Docker Container
        run: |
          docker stop cicd-test-container || true
          docker rm cicd-test-container || true
          docker run -d -p 8000:8000 --name cicd-test-container alirhayem/docker-cicd-test:latest
